### ISSUE TITLE
Mac: tab completion doesn't work for branches

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#169]
I have a mac now! Trying to use Git on Terminal has some limitations. Specifically, I'm used to using tab-completion for branch names. 

```
$ git push fork myB<tab>
$ git push fork myBranch
```

This does not appear to work on the Mac in Terminal. Is it something wrong with our install, or is the supplied tab-completion not wired correctly for Mac?

**Comment by dscho** [comment]
> is the supplied tab-completion not wired correctly for Mac?

You can find out by calling `set | less "+/^_git "`; This should show you the `_git` shell function; Here, it looks like this:

```sh
__git ()
{
    git ${__git_C_args:+"${__git_C_args[@]}"} ${__git_dir:+--git-dir="$__git_dir"} "$@" 2> /dev/null
}
```
