### ISSUE TITLE
Changed paths Bloom filters

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#175]
* [Supercharging the Git Commit Graph IV: Bloom Filters](https://devblogs.microsoft.com/devops/super-charging-the-git-commit-graph-iv-bloom-filters/) [_ugh... the animations are not loading... they converted the blog but broke the animated pngs_]

* [This branch in derrickstolee/git has a prototype](https://github.com/derrickstolee/git/tree/bloom/stolee)

* [This discussion on the list](https://public-inbox.org/git/61559c5b-546e-d61b-d2e1-68de692f5972@gmail.com/) is a starting point for the discussion. Read the replies and the context for full details.

Future directions after first implementation:

* [A discussion about how Bloom filters didn't fix `git blame`](https://public-inbox.org/git/CABXAcUzoNJ6s3=2xZfWYQUZ_AUefwP=5UVUgMnafKHHtufzbSA@mail.gmail.com/)

* #166

**Comment by derrickstolee** [comment]
I can't seem to assign this to @garimasi514. Is there something missing with her membership to the microsoft org? Something in this specific repo? cc/ @jrbriggs

**Comment by wilbaker** [comment]
@garimasi514 you might need to join https://github.com/orgs/microsoft/teams/git-for-windows-collaborators/members

**Comment by derrickstolee** [comment]
I was able to find one of the animations:

![commit-graph-bloom](https://user-images.githubusercontent.com/570044/63122465-d6a8a980-bf74-11e9-8130-74df71f2ab3f.png)

**Comment by garimasi514** [comment]
@wilbaker Thanks! I have been trying to join that team for a while.. i think one of my requests went through and it won't let me request again. Maybe @jrbriggs can see my request somewhere?

**Comment by jrbriggs** [comment]
@garimasi514 I've added you to the group

**Comment by derrickstolee** [comment]
These are all merged to `master` upstream!
