### ISSUE TITLE
Sparse-checkout: respect `core.ignoreCase`

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#224]
For this issue, assume we are in "cone mode" with `core.sparseCheckoutCone` enabled.

The `git sparse-checkout set` command currently converts a list of paths into prefix patterns that will update the working directory to only include files in those folders (or adjacent to those folders). If the given patterns do not match in case, then those folders will not be included.

To resolve these case issues, perform the following check in the `set` subcommand when `core.ignoreCase` is enabled:

1. For each pattern, check if it matches an existing pattern in the index.
2. If there is no matching pattern, attempt finding an alternate case.
3. If an alternate casing is found, then save that pattern instead. (This prevents performance issues in the many more workdir-changing commands such as `git checkout`).
4. (Optional) If no alternate casing is found, then fail, perhaps only when `--strict` is specified.

**Comment by dscho** [comment]
Would it not make more sense to imitate the way `name-hash.c` operates, i.e. using `memihash()` (or `strihash()`?

**Comment by derrickstolee** [comment]
This is resolved upstream and in #233
