### ISSUE TITLE
Disable "git update" and "git update-git-for-windows" in VFS versions

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#241]
If a user runs [`git update-git-for-windows`](https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-update-git-for-windows), then they will upgrade to a version that does not support microsoft/vfsforgit or microsoft/scalar.

Find a way to disable this so users do not [up/down]grade in error.

**Comment by dscho** [comment]
> Find a way to disable this so users do not [up/down]grade in error.

I think that's easy: just implement a dummy built-in. I'll try my hand at this, please give me a few minutes.

**Comment by dscho** [comment]
Closed via #243
