### ISSUE TITLE
Odd compile error with RES_STARTEND and regex.h version on MSVC build

### ISSUE THREAD

**Issue by jeffhostetler** [microsoft/git#275]
I think I've found a problem in the Makefile for v2.27.0.  (I haven't tracked it back to when it first appeared yet.)

Basically, when building the MSVC version (using `make MSVC=1 DEBUG=1`) I'm seeing an error

    ...
    fuzz-commit-graph.c
    C:\work\msft\git-compat-util.h(1135): fatal error C1189:
        #error:  "Git requires REG_STARTEND support. Compile with NO_REGEX=NeedsStartEnd"
    ...

However, we're already defining that symbol in `config.mak.uname` in the MSVC section.

Hacking the Makefile to include `-E` and looking at the CPP output shows that the compiler is
finding the wrong version of `regex.h`.  It is finding:

    ...
    __pragma(pack(pop))
    #line 189 "C:\\work\\msft\\git-compat-util.h"
    #line 1 "C:\\git-sdk-64\\mingw64\\include\\regex.h"
    ...

and NOT the one in `./compat/regex/regex.h`

Note that the MSVC section in `config.mak.uname` is adding `-Icompat -Icompat/regex` to `COMPAT_FLAGS`  at https://github.com/microsoft/git/blob/vfs-2.27.0/config.mak.uname#L451  (and later again at https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L1793 )

Later, `COMPAT_CFLAGS` gets appended to `BASIC_CFLAGS` at https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L2004

**BUT** At https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L1357-L1381
(and when `CURLDIR` is `mingw64`) we append `-I/mingw64/include` to `BASIC_CFLAGS`,
but this happens before `COMPAT_CFLAGS` is appended.

Therefore, the compiler sees `... -I/mingw64/include -Icompat -Icompat/regex ...`
and tries to use the wrong version of `regex.h` which leads to the compiler error.

I'm not sure if this problem is unique to a conflict with CURL.  It looks like it Expat, ZLib, 
IConv, and a few others could similarly update `BASIC_CFLAGS` before the values from
`COMPAT_CFLAGS` are brought in.

Thoughts??

**Comment by jeffhostetler** [comment]
https://github.com/jeffhostetler/git/commit/7533abbd04e90aa127ebdbc2b4c382793e7dc526

This the `-E` hack.  Use it with `make MSVC=1 DEBUG=1 CFLAGS="-E"`.
I'm not creating a PR for this now, since the real fix should be upstream rather than here.
And this hack could go with it.

**Comment by dscho** [comment]
Where does that `-I/mingw64/include` come from? That should _not_ be there, MSVC cannot handle those headers.

**Comment by jeffhostetler** [comment]
Either of these lines, I think.
https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L1366
https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L1379

Here's what I get when I look at curl-config:

    $ curl-config --cflags
    -I/mingw64/include

So we get that stuck into `CURL_CFLAGS` and that gets appended onto `BASIC_CFLAGS`
at https://github.com/microsoft/git/blob/vfs-2.27.0/Makefile#L1381 .

**Comment by jeffhostetler** [comment]
So the resulting command line looks like this.  I suggest that the `-I` is coming from the
CURL block because it appears between the `HAVE_ALLOCA_H` and the `USE_CURL_FOR_IMAP_SEND` terms.


```
www.txt:8040:compat/vcbuild/scripts/clink.pl -o fuzz-commit-graph.o -c
-nologo -I. -Icompat/vcbuild/include -DWIN32 -D_CONSOLE -DHAVE_STRING_H
-D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -I"C:\work\msft\compat\vcbuild\vcpkg\installed\x64-windows\include"
-I"C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt"
-I"C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um"
-I"C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared"
-I"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/INCLUDE"
-L"C:\work\msft\compat\vcbuild\vcpkg\installed\x64-windows\debug\lib"
-L"C:/Program Files (x86)/Windows Kits/10/lib/10.0.18362.0/ucrt/x64"
-L"C:/Program Files (x86)/Windows Kits/10/lib/10.0.18362.0/um/x64"
-L"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/lib/x64"
-Zi -MDd -DDEBUG -D_DEBUG -DGIT_HOST_CPU="\"x86_64\""
-DHAVE_ALLOCA_H -I/mingw64/include -DUSE_CURL_FOR_IMAP_SEND -DNO_ST_BLOCKS_IN_STRUCT_STAT
-DNO_SYMLINK_HEAD -DNO_GETTEXT -DNO_POLL_H -DNO_SYS_POLL_H -DNO_INTTYPES_H -DMMAP_PREVENTS_DELETE
-DNO_IPV6 -DNO_UNIX_SOCKETS -DNO_POSIX_GOODIES -DSHA1_DC -DSHA1DC_NO_STANDARD_INCLUDES
-DSHA1DC_INIT_SAFE_HASH_DEFAULT=0 -DSHA1DC_CUSTOM_INCLUDE_SHA1_C="\"cache.h\""
-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C="\"git-compat-util.h\"" -DSHA256_BLK  -DUNRELIABLE_FSTAT
-DNATIVE_CRLF -DHAVE_WPGMPTR -D__USE_MINGW_ACCESS -DDETECT_MSYS_TTY -DENSURE_MSYSTEM_IS_SET
-DNOGDI -DHAVE_STRING_H -Icompat -Icompat/regex -Icompat/win32 -DSTRIP_EXTENSION=\".exe\"
-DNO_LIBGEN_H -DNO_POLL -Icompat/poll -DNO_STRCASESTR -DNO_STRLCPY -DNO_STRTOUMAX -DNO_SETENV -DNO_MKDTEMP
-DUSE_WIN32_MMAP -DOBJECT_CREATION_MODE=1 -DNO_PREAD -DNO_MEMMEM
-DRUNTIME_PREFIX -Icompat/regex -DSHELL_PATH='"/bin/sh"' -DDEFAULT_HELP_FORMAT='"html"'
-DPAGER_ENV='"LESS=FRX LV=-c"'
fuzz-commit-graph.c
```

**Comment by dscho** [comment]
>  [...] it appears between the `HAVE_ALLOCA_H` and the `USE_CURL_FOR_IMAP_SEND` terms.

Ah, it's most likely caused by https://github.com/git-for-windows/git/blob/v2.27.0.windows.1/Makefile#L1374.

As this was kind of intentional, maybe our best bet is to add an `if` clause before https://github.com/git-for-windows/git/blob/v2.27.0.windows.1/compat/vcbuild/scripts/clink.pl#L26 that skips `-I/mingw{32,64}/...`?
