### ISSUE TITLE
GVFS-Helper: Fail harder on failed write?

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#279]
A build machine recently had failures in `git status` with the following logs:

```
Running git status...
open2: exec of watchman -j --no-pretty failed at /Volumes/DataB/og1/src/.git/hooks/query-watchman line 47.
error: gvfs-helper error: 'could not create tempfile: '/Users/bud/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414/pack/tempPacks/t-20200625-025012-165469-0000-5.temp': from GET 0751ff206365fa35c07e154bfe4500e2db5f5676'
error: gvfs-helper died of signal 15
error: gvfs-helper error: 'could not create tempfile: '/Users/bud/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414/pack/tempPacks/t-20200625-025012-631659-0000-5.temp': from POST'
error: gvfs-helper died of signal 15
```

However, the `git status` appears to have completed "successfully", which was confusing. Perhaps we should fail harder when the `git-gvfs-helper` has this kind of failure.

**Comment by jeffhostetler** [comment]
Here are a few notes I made while digging into this.

The first line `error: gvfs-helper error:` was printed by the foreground command. (Maybe `status`.)  It is echoing the
error buffer that `gvfs-helper` sent back across the long-running subprocess pipe/socket (and received in
`gh_client__objects__receive_response()`).

```
error: gvfs-helper error: 'could not create tempfile: '/Users/bud/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414/pack/tempPacks/t-20200625-025012-165469-0000-5.temp': from GET 0751ff206365fa35c07e154bfe4500e2db5f5676'
```

After `gvfs-helper` returns an error to the client, the client calls `subprocess_stop()` which sends a `SIGTERM` (15) to
the child process.  When the client reaps the child it sees the 15 and prints the second message.  This happens in
`gh_client__drain_queue()`, `gh_client__get_immediate()`, and `gh_client__prefetch()`.

```
error: gvfs-helper died of signal 15
```

I can't tell from this log if the `git status` spawned both instances of `gvfs-helper` or if there's another client
command in the mix.  It is possible that the first was a GET on a tree and after the cleanup following the SIGTERM,
that the client launched another one for the POST.

It's weird that these would fail to create a temp file.

The caller of `gh_client__*()` in the client does not abort on an error from `gvfs-helper`.  This allows it to fallback
(in `do_oid_object_info_extended()`) to other techniques (the `read_object_hook()` and the promisor stuff).

**Comment by jeffhostetler** [comment]
This is 4 years old and hasn't been reported since. I'm going to close this.
