### ISSUE TITLE
git-gvfs-helper: be more careful around bad prefetch packs

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#299]
A user reported an error of the form

```
error: index file C:/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414/pack/prefetch-1869771333-6573743e645f5f32352e4d6f76654e6578742829.idx is too small
```

The `.idx` file had 0 bytes, so my default thought was an `fsync()` issue.

I recommended that they delete the `.idx` and the `multi-pack-index` then run `git index-pack` on that pack file. However, that failed, as well:

```
C:\...\src>git index-pack C:/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414/pack/prefetch-1869771333-6573743e645f5f32352e4d6f76654e6578742829.pack
fatal: pack signature mismatch
```

This is possibly due to not catching an fsync inside `git-gvfs-helper` when the download cut short. Possibly the `index-pack` command we run failed, but for some reason allowed the prefetch to complete with success.

We need to make this more robust!

**Comment by jeffhostetler** [comment]
This message is thrown from index-pack while reading the header record in the packfile.  This error
means that the first 4 bytes are not "PACK".  It also means that the file did have at least 4k of data
(just ruling out zero byte truncated packfile).

Can we get the packfile from the reporting user ??  (Not sure it's necessary if it'd be a pain; just asking.)

**Comment by derrickstolee** [comment]
Closing as no repro until we find a need for it later.
