### ISSUE TITLE
Scalar clone: make 404s on `gvfs/config` silent

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#384]
I ran `scalar clone` against a GitHub URL and saw these lines in the output:

```
error: config: (http:404) Not Found
error: config: (http:404) Not Found
```

These are likely related to the `/gvfs/config` endpoint, which doesn't exist on GitHub (and many others). This error is likely being output from Curl, but we should pass the correct option to make this be silent.

**Comment by dscho** [comment]
I bet that it is both from `/gvfs/config` and `/vsts/info` (there are two messages, after all). And I think the error messages are generated here:

- https://github.com/microsoft/git/blob/v2.32.0.vfs.0.2/gvfs-helper.c#L3599
- https://github.com/microsoft/git/blob/v2.32.0.vfs.0.2/gvfs-helper.c#L3628

The work-around is most likely to guard the message behind `ec != GH__ERROR_CODE__HTTP_404`.

**Comment by yash112-lang** [comment]
Hello, @derrickstolee, is this issue is still open I like to work on this issue. I am new to open source & want to contribute.

**Comment by derrickstolee** [comment]
Hi @yash112-lang. Yes, this issue is still open. Please start looking at those lines that @dscho links above. Let us know if you have trouble. Thanks!

**Comment by denizariyan** [comment]
Hi @derrickstolee, is this issue still open? I see that #504 is open but don't think it is actively being worked on right now.

**Comment by derrickstolee** [comment]
Thanks, @denizariyan for the reminder. Is @abdurraheemali around to comment on whether they will continue with this work? @dscho supplied some recommended changes, but we're exited to see a contribution helping in this area.

**Comment by abdurraheemali** [comment]
> Thanks, @denizariyan for the reminder. Is @abdurraheemali around to comment on whether they will continue with this work? @dscho supplied some recommended changes, but we're exited to see a contribution helping in this area.

I totally forgot I had a PR open here. I'll probably continue with it today.
