### ISSUE TITLE
GVFS Prefetch runs into rate limits on Azure DevOps

### ISSUE THREAD

**Issue by abdurraheemali** [microsoft/git#482]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/98995519/152459388-f4710101-edac-4575-9bc3-4983100d992e.png">

The global consumption limit is 200 TSTUs within a sliding five-minute window. Exceeding this gets us throttled down to 0-12 TSTUs every 5 minutes. Can we change the prefetch to stay just under the threshold?

https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

git version 2.33.0.vfs.0.3
cpu: x86_64
built from commit: 7e354fb19cf049c46b94750aa639efd1468b94a1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11 64 bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.434]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Microsoft internal

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
scalar clone --full-clone (some large azure devops repo link)
```
 - What did you expect to occur after running these commands?

The repo should have been downloaded within ~20 mins

 - What actually happened instead?

It ran into rate limits and got throttled by a lot.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://o365exchange.visualstudio.com/O365%20Core/_git/Nibiru

**Comment by abdurraheemali** [comment]
I updated to git/2.35.1.vfs.0.0 and it works better now. Seems this was already handled by 

https://github.com/microsoft/git/commit/3221f52b54378835694b3731d6a1b0093a035088#diff-c2fce35a544e22637e0311c1f6a79480f092dc07d54e3924857c6ba50b64ac68

**Comment by abdurraheemali** [comment]
![image](https://user-images.githubusercontent.com/98995519/152624101-3f79ee22-c48c-40d3-beeb-dd6b820526dd.png)
 
Reopening since it still happens on the latest version. It would be really cool to say "I submitted a patch to git", so instead of fixing it yourself, maybe give me a hint and I'll try helping out? It seems like using this struct in the logic that determines when to call do_throttle_spin or do_throttle_wait could work.

https://github.com/microsoft/git/blob/2f6531aced2e77a6c1000a923967ae0105383930/gvfs-helper.c#L405-L412 

In particular, I would think about how to change this so that we have a more reliable backoff during prefetch that somewhat consistently does not exceed the threshold (without making any promises/guarantees that it will _never_ exceed the threshold, which would be hard to coordinate across processes). Especially considering that something outside git could cause us to go over.

https://github.com/microsoft/git/blob/2f6531aced2e77a6c1000a923967ae0105383930/gvfs-helper.c#L2761-L2771

**Comment by derrickstolee** [comment]
Hi @abdurraheemali. You will need to contact Azure DevOps support to get assistance with the GVFS endpoints and their rate limits.

The general approach in the past is to set up GVFS Cache Servers (they are self-hosted instances of Azure DevOps Server configured to serve GVFS data) and in those cases you will not hit rate limits because most of the data is downloaded from servers you own.

**Comment by abdurraheemali** [comment]
Thanks! We have six gvfs cache servers set up now in a couple of regions. 

`<appSettings>
  
    <add location="USWEST" url="https://ossgvfs.redmond.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
    <add location="NORTHEUROPE" url="https://ossgvfs.europe.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
    <add location="SOUTHEASTASIA" url="https://ossgvfs.fareast.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
    <add location="OSLO" url="https://oslogvfs.europe.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
    <add location="CHINA" url="https://ossgvfs.fareast.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
    <add location="SUZHOU" url="https://szgvfs.fareast.corp.microsoft.com/ee6fb219f8924d029e965c16fe59c175"/>
  </appSettings>`

> "If the remote supplies a list of cache servers via the <url>/gvfs/config endpoint"

https://o365exchange.visualstudio.com/O365%20Core/_git/Substrate/gvfs/config shows

{"AllowedGvfsClientVersions":[{"Min":{"Major":0,"Minor":0,"Build":0,"Revision":0},"Max":null}],"CacheServers":[{"Url":"https://ossgvfs.redmond.corp.microsoft.com/ee6fb219-f892-4d02-9e96-5c16fe59c175","Name":"Redmond","GlobalDefault":true}]}

How do we add those cache servers here?

https://github.com/Microsoft/VFSForGit/blob/master/Protocol.md just says it's "server set"

**Comment by dscho** [comment]
> How do we add those cache servers here?

That's an Azure DevOps question, not a Git question. Please contact your Azure DevOps support to address this.

**Comment by abdurraheemali** [comment]
That's fair. I'll close this issue then. Thanks for the help again!
