### ISSUE TITLE
git update-microsoft-git does not install updates

### ISSUE THREAD

**Issue by ghost** [microsoft/git#489]
- [ X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.vfs.0.0
cpu: x86_64
built from commit: 24f9d5c95d3ab8fe65553b8d488e1b287eda8e42
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1526]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Output is from -> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I'm aware.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 7.2.1

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git --version
git update-microsoft-git
git --version

//Output:
PS C:\Users\doug.murphy> git --version
git version 2.33.0.vfs.0.0
PS C:\Users\doug.murphy> git update-microsoft-git
Git 2.33.0.vfs.0.0 (64-bit)
PS C:\Users\doug.murphy> git --version
git version 2.33.0.vfs.0.0

```
 - What did you expect to occur after running these commands?

That my installation of Git would be updated to the latest from this GitHub repo (v2.35.1.vfs.0.0 at the time of this writing)

 - What actually happened instead?

Nothing. The update did not occur. No mention of any available update.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by derrickstolee** [comment]
Hello, and thanks for the report.

I believe that this issue is a known one and fixed in later builds. For instance, you can try installing [v2.34.1.vfs.0.0](https://github.com/microsoft/git/releases/tag/v2.34.1.vfs.0.0) and it will both prompt daily for updates and also work with `git update-microsoft-git`. (_Edit:_ Currently, trying this will upgrade you to v2.35.1.vfs.0.0.)

**Comment by ghost** [comment]
@derrickstolee Looks like you are correct. I installed 2.34.1.vfs.0.0 and then tried the `git update-microsoft-git` command again. It showed that 2.35.1.vfs.0.0 was available, prompted me to install, and installed successfully.

Thanks for the prompt response!
