### ISSUE TITLE
multi-pack-index expire doesn't do anything if --objects-dir contains backward slashes

### ISSUE THREAD

**Issue by nikola-sh** [microsoft/git#497]
VFSForGit runs `PackfileMaintenanceStep` periodically, but content of `pack` subdirectory in `.gvfsCache` remains unchanged.
The reason is that `git multi-pack-index expire` command doesn't work with backward slash paths for `--object-dir` (see reproduction example below).
So VFSForGit runs `expire` with backward slashes and it doesn't do anything.
It seems git behavior should not depend on paths format.

 - [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?
```
git version 2.36.0.vfs.0.0
cpu: x86_64
built from commit: 5323cc6ccf2923f4f41da713ea9d1125704dec5b
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

`VFS for Git`

If VFS for Git, then what version?

```
$ gvfs version

v1.0.21229.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1645]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

If you run `multi-pack-index expire` with backward slashes for `--object-dir` command do nothing
```
c:\Windows>"C:\Program Files\Git\mingw64\bin\git.exe" --git-dir="F:\Projects\Monorepo\src\.git" -c core.virtualizeobjects=false multi-pack-index expire --object-dir="F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects"
13:16:41.308775 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:16:41.310776 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:41.310776 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/pre-command.exe multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects' --git-pid=31564
13:16:41.404016 run-command.c:1581      run_processes_parallel: done
13:16:41.404016 git.c:531               trace: built-in: git multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects'
13:16:41.410589 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:41.410589 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/post-command.exe multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects' --git-pid=31564 --exit_code=0
13:16:41.497558 run-command.c:1581      run_processes_parallel: done
```

Command starts doing smth with forward slashes for `--object-dir`:
```
c:\Windows>"C:\Program Files\Git\mingw64\bin\git.exe" --git-dir="F:\Projects\Monorepo\src\.git" -c core.virtualizeobjects=false multi-pack-index expire --object-dir="F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects"
13:16:56.612496 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:16:56.615528 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:56.615528 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/pre-command.exe multi-pack-index expire --object-dir=F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects --git-pid=34208
13:16:56.715399 run-command.c:1581      run_processes_parallel: done
13:16:56.715399 git.c:531               trace: built-in: git multi-pack-index expire --object-dir=F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects
Unlink of file 'F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects/pack/from-loose-922b0b1f773d613ed0ae0a493433d10461ae7c4f.idx' failed. Should I try again? (y/n)
```

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [ ] Public repo: **insert URL here**
   * [ ] Windows monorepo
   * [ ] Office monorepo
   * [ ] Other Microsoft-internal repo: **insert name here**
   * [x] Other internal repo.

**Comment by derrickstolee** [comment]
Thanks, @nikola-sh. I've confirmed that VFS for Git sends the path in the format you are describing AND that the `expire` (and `repack`) commands do nothing here.

The root cause is an upstream change in how we found the existing multi-pack-index from the given `--object-dir` in a more-strict way than before.

This bug only affects VFS for Git. Scalar uses Git's background maintenance, which passes the paths in the Unix style already.

I'll send a fix into `microsoft/git` soon, but it also applies upstream.
