### ISSUE TITLE
Improve documentation: Is this fork still needed for non-GVFS workflows?

### ISSUE THREAD

**Issue by phoerious** [microsoft/git#517]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

This is a suggestion to update the description with information on whether (and why) this fork is still needed if you have an up-to-date upstream Git client.

From my understanding, the original project was GVFS, which is practically dead. The next thing after that was Scalar, which has so far been superseded by this repository. Now unless I am using a remote via the GVFS protocol (which I'm not), it is not quite clear to me whether I still need this fork. The `scalar` CLI command seems to be a useful yet optional thin-wrapper around the initial `git clone` that sets up recommended `.git/config` settings, but other than that, I don't really see any difference between this fork and the upstream project, both in terms of functionality and performance. It would be great if the documentation could be more clear on this.

**Comment by derrickstolee** [comment]
VFS for Git is in maintenance mode, but is still actively used by the Windows OS repository. The custom logic for the GVFS protocol is critical to the Office monorepo's use of Scalar with Azure DevOps. This fork will be necessary as long as those monorepos are on Azure DevOps.

**Comment by phoerious** [comment]
That's what I understood from the description. But does that also mean that besides the scalar CLI there is no difference between this fork and the upstream project for non-GVFS repositories? If so, then I could simply use the normal upstream git + the Scalar-created gitconfig.
