### ISSUE TITLE
v2.37.x Windows installers do not appear to be codesigned correctly

### ISSUE THREAD

**Issue by AtOMiCNebula** [microsoft/git#519]
I don't get any codesigning/SmartScreen warnings when downloading+installing [Git-2.36.1.vfs.0.0-64-bit.exe](https://github.com/microsoft/git/releases/download/v2.36.1.vfs.0.0/Git-2.36.1.vfs.0.0-64-bit.exe), but I do when downloading either [Git-2.37.0.vfs.0.0-64-bit.exe](https://github.com/microsoft/git/releases/download/v2.37.0.vfs.0.0/Git-2.37.0.vfs.0.0-64-bit.exe) or [Git-2.37.1.vfs.0.0-64-bit.exe](https://github.com/microsoft/git/releases/download/v2.37.1.vfs.0.0/Git-2.37.1.vfs.0.0-64-bit.exe).  On the surface, the two EXEs appear to have digital signatures on them, but when running them, the elevation dialog says Unknown Publisher, and Edge/SmartScreen give big warnings about it being an unknown publisher.  Release notes say these releases had build/release workflow changes, so I wanted to bubble this up.

![image](https://user-images.githubusercontent.com/922096/179567259-9dd059f3-2f2d-4b1d-bf35-ed41fad6dbf9.png)

![image](https://user-images.githubusercontent.com/922096/179567411-7acc5311-7b80-4de0-9de7-e1d2cbe0cd05.png)

![image](https://user-images.githubusercontent.com/922096/179567491-dda7a472-dcf5-4d2e-9dcb-67368f9b0ebd.png)

**Comment by AtOMiCNebula** [comment]
![image](https://user-images.githubusercontent.com/922096/179567890-8658db2f-760e-40f4-907d-e9b845917982.png)

cc @dscho

**Comment by derrickstolee** [comment]
@dscho and @ldennington please advise. We likely need to update a secret here in the `microsoft/git` repository and re-run the installer builds.

**Comment by ldennington** [comment]
@dscho - I believe you already completed the steps to get a new certificate for Git for Windows, right?

**Comment by AtOMiCNebula** [comment]
Ping? 😄

**Comment by ldennington** [comment]
Sorry @AtOMiCNebula - we cannot fix this until Johannes gets back because he has the new cert. Are you seeing this issue even when you try to update with `git update-microsoft-git`?

**Comment by AtOMiCNebula** [comment]
Yep, I still see the elevation dialog warning with "Publisher: Unknown" (third screenshot in my initial post) through the auto-updater.  I don't see SmartScreen errors (since that's an Edge feature).

FWIW, it is arguably a security issue that the Git auto-updater is not ensuring that the installer binaries it downloads are appropriately signed.  But, one issue at a time, I suppose. 😇

**Comment by ldennington** [comment]
We discussed internally and have moved v2.37.1.vfs.0.0 back to pre-release in light of this issue, which should stop the auto-updater from prompting users who have not yet done so to upgrade. We're planning to send a notification of this decision to our Microsoft partners shortly. Thanks for raising it up @AtOMiCNebula.

**Comment by dscho** [comment]
> @dscho - I believe you already completed the steps to get a new certificate for Git for Windows, right?

My apologies, I was on vacation. And yes, I got the new certificate already a long time ago, but forgot to update the repository secret in this here repository, sorry! This is fixed in the meantime.

**Comment by AtOMiCNebula** [comment]
No worries, @dscho!  The new v2.37.1.vfs.0.1 release looks good to me. 🥳
