### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by Eli-Black-Work** [microsoft/git#527]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

In `Readme.md`, there's a link to [Scalar user guide](https://github.com/microsoft/git/blob/vfs-2.37.2/Documentation/scalar/index.md). The link leads to a 404 🙂

**Comment by dscho** [comment]
@Bosch-Eli-Black good point. I think it should be pointing to https://github.com/microsoft/git/blob/vfs-2.37.2/contrib/scalar/docs/index.md.

**Comment by Eli-Black-Work** [comment]
Thanks! 🙂
