### ISSUE TITLE
warning: fetch normally indicates which branches had a forced update

### ISSUE THREAD

**Issue by Eli-Black-Work** [microsoft/git#534]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

```
$ git --version --build-options

git version 2.37.1.vfs.0.1
cpu: x86_64
built from commit: 196b322ff5c5f86d9c1e16b91dda9518ac7a7afe
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Uuuuh... neither, I think? I'm using this fork of Git with a normal Git repo on BitBucket 🙂

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1889]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

No warnings

 - What actually happened instead?

I get the following warning:
```
C:\sources\>git pull
warning: fetch normally indicates which branches had a forced update,
but that check has been disabled; to re-enable, use '--show-forced-updates'
flag or run 'git config fetch.showForcedUpdates true'
Already up to date.
```

I believe this warnings started occurring after I switched from Git for Windows to Microsoft's fork of Git, but I'm not 100% sure. If this warning is due to switching to Microsoft's fork of Git, then I think that running `scalar initialize` should automatically set `fetch.showForcedUpdates` to `true` or `false` 🙂

**Comment by derrickstolee** [comment]
This is purposefully set as off because the time it takes to check force pushes is too expensive in large monorepos with significant commit history.

You can remove this message by running `git config --global advice.fetchShowForcedUpdates false`.

**Comment by Eli-Black-Work** [comment]
Got it. Thanks! 🙂
