### ISSUE TITLE
"git log" takes too much time than I think

### ISSUE THREAD

**Issue by miku1958** [microsoft/git#546]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.vfs.0.0
cpu: x86_64
built from commit: 0de34d54680002380b4e1adad74db64a34e03053
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

zsh

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git --no-pager log HEAD --branches --remotes --tags --max-count=1 --topo-order
```
 - What did you expect to occur after running these commands?

Finish as fast as possible

 - What actually happened instead?

When adding more and more options, it takes more time than I think, I do the test start with `git --no-pager log HEAD --max-count=1` and here is the result:

>git --no-pager log HEAD --max-count=1 > /dev/null  0.08s user 0.59s system 90% cpu 0.746 total
git --no-pager log HEAD --max-count=1 --topo-order > /dev/null  15.67s user 2.86s system 97% cpu 19.091 total
git --no-pager log HEAD --branches --max-count=1 --topo-order > /dev/null  15.50s user 2.95s system 97% cpu 18.960 total
git --no-pager log HEAD --branches --remotes --max-count=1 --topo-order >   22.76s user 3.88s system 97% cpu 27.336 total

You can see, once I added --topo-order or --remotes, it took a lot of time to complete

I also tested it with standard git, and it is faster a lot:

>/usr/bin/git --no-pager log HEAD --max-count=1 > /dev/null  0.08s user 0.66s system 89% cpu 0.828 total
/usr/bin/git --no-pager log HEAD --branches --remotes --tags --max-count=1  >  12.27s user 3.31s system 95% cpu 16.261 total

here is the full stack:
>% git --no-pager log HEAD --branches --remotes --tags --max-count=1 --topo-order
15:14:48.955803 common-main.c:49             | d0 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
15:14:48.956264 common-main.c:50             | d0 | main                     | start        |     |  0.001319 |           |              | git --no-pager log HEAD --branches --remotes --tags --max-count=1 --topo-order
15:14:48.956874 repository.c:136             | d0 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
15:14:48.957489 git.c:533                    | d0 | main                     | cmd_name     |     |           |           |              | log (log)
15:14:48.963141 midx.c:173                   | d0 | main                     | data         | r1  |  0.008199 |  0.008199 | midx         | load/num_packs:114
15:14:48.963160 midx.c:174                   | d0 | main                     | data         | r1  |  0.008222 |  0.008222 | midx         | load/num_objects:6572781
commit 65d936e75125a146a5314c1b74c58828535270b3 (origin/main)
Merge: 263aed517b74 d78271abd027
Author: AutoMerge <omerge@microsoft.com>
Date:   Sat Nov 19 06:40:28 2022 +0000
>
>    AUTO-MERGE: TASMAN RI - lkg/tasman/to/main to main
15:15:13.815637 git.c:796                    | d0 | main                     | exit         |     | 24.860697 |           |              | code:0
15:15:13.815665 revision.c:3448              | d0 | main                     | data_json    | r1  | 24.860726 | 24.860726 | topo_walk    | statistics:{"count_explore_walked":365992,"count_indegree_walked":365992,"count_topo_walked":1}
15:15:13.815676 trace2/tr2_tgt_perf.c:215    | d0 | main                     | atexit       |     | 24.860737 |           |              | code:0

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [x] Office monorepo

**Comment by derrickstolee** [comment]
If `--topo-order` is taking so long, then it probably means that you don't have a `commit-graph` file, or it is out of date.

Please run `scalar reconfigure` in your repository, or `scalar reconfigure --all` to be sure that background maintenance is properly running in your repository or repositories. You can also run `git maintenance run --task=commit-graph` to get an up-to-date `commit-graph` file which should immediately improve the performance. (The background maintenance is important to keeping your commands running smoothly over time as your repository grows.)

**Comment by miku1958** [comment]
Thanks @derrickstolee, let me try

**Comment by miku1958** [comment]
I fixed this by rebuilding my shared cache.
