### ISSUE TITLE
Multi-threaded support for label:objects/get from gvfs-helper

### ISSUE THREAD

**Issue by miku1958** [microsoft/git#551]
I found in this [issue](https://github.com/microsoft/git/issues/542#issuecomment-1330173967) that my ScalarSache seems to be broken, my ScalarSache is close to 60G, so I want to delete it and rebuild it, but the process is very slow, most of the time is re-fetching objects, it only use single thread to do the job. Is it possible to increase this number of simultaneous fetches to higher?

This is the call path:
>11:34:38.200755 common-main.c:49             | d0 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
11:34:38.201670 common-main.c:50             | d0 | main                     | start        |     |  0.013245 |           |              | scalar reconfigure --all
11:34:38.203264 common-main.c:59             | d0 | main                     | exit         |     |  0.015190 |           |              | code:0
11:34:38.203281 trace2/tr2_tgt_perf.c:215    | d0 | main                     | atexit       |     |  0.015208 |           |              | code:0
11:34:38.211528 common-main.c:49             | d0 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
11:34:38.211941 common-main.c:50             | d0 | main                     | start        |     |  0.001100 |           |              | git maintenance run --task=commit-graph
11:34:38.213200 repository.c:136             | d0 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
11:34:38.214240 git.c:533                    | d0 | main                     | cmd_name     |     |           |           |              | maintenance (maintenance)
11:34:38.215634 builtin/gc.c:1345            | d0 | main                     | region_enter | r1  |  0.004795 |           | maintenance  | label:commit-graph
11:34:38.215678 run-command.c:722            | d0 | main                     | child_start  |     |  0.004838 |           |              | ..[ch0] class:? argv:[git commit-graph write --split --reachable]
11:34:38.221221 common-main.c:49             | d1 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
11:34:38.221741 common-main.c:50             | d1 | main                     | start        |     |  0.001505 |           |              | /usr/local/git/libexec/git-core/git commit-graph write --split --reachable
11:34:38.222361 repository.c:136             | d1 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
11:34:38.222938 git.c:533                    | d1 | main                     | cmd_name     |     |           |           |              | commit-graph (maintenance/commit-graph)
11:34:38.223549 builtin/commit-graph.c:240   | d1 | main                     | cmd_mode     |     |           |           |              | write
11:34:38.223666 progress.c:268               | d1 | main                     | region_enter | r1  |  0.003434 |           | progress     | label:Collecting referenced commits
11:34:38.321981 gvfs-helper-client.c:488     | d1 | main                     | printf       |     |  0.101748 |           |              | ..gh_client__get_immediate: 51c4c507b8b0a594f5fd2b27d32831c8e0dff3e9
11:34:38.322019 run-command.c:722            | d1 | main                     | child_start  |     |  0.101786 |           |              | ..[ch0] class:subprocess argv:[git gvfs-helper --fallback --cache-server=trust --shared-cache=/Volumes/Builds/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414 server]
11:34:38.327741 common-main.c:49             | d2 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
11:34:38.327970 common-main.c:50             | d2 | main                     | start        |     |  0.001303 |           |              | /usr/local/git/libexec/git-core/git gvfs-helper --fallback --cache-server=trust --shared-cache=/Volumes/Builds/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414 server
11:34:38.328584 git.c:819                    | d2 | main                     | cmd_name     |     |           |           |              | _run_dashed_ (maintenance/commit-graph/_run_dashed_)
11:34:38.328601 run-command.c:722            | d2 | main                     | child_start  |     |  0.001940 |           |              | [ch0] class:dashed argv:[git-gvfs-helper --fallback --cache-server=trust --shared-cache=/Volumes/Builds/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414 server]
11:34:38.356855 common-main.c:49             | d3 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
11:34:38.357785 common-main.c:50             | d3 | main                     | start        |     |  0.008614 |           |              | /usr/local/git/libexec/git-core/git-gvfs-helper --fallback --cache-server=trust --shared-cache=/Volumes/Builds/.scalarCache/id_ba47400f-eebe-4850-a8bf-ef694ef81414 server
11:34:38.358706 gvfs-helper.c:4182           | d3 | main                     | cmd_name     |     |           |           |              | gvfs-helper (maintenance/commit-graph/_run_dashed_/gvfs-helper)
11:34:38.360510 repository.c:136             | d3 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
11:34:38.363184 gvfs-helper.c:4077           | d3 | main                     | cmd_mode     |     |           |           |              | server
11:34:38.365111 gvfs-helper.c:1335           | d3 | main                     | data         |     |  0.016306 |  0.016306 | gvfs-helper  | remote/url:https://dev.azure.com/office/office/_git/Office
11:34:38.368521 gvfs-helper.c:1394           | d3 | main                     | data         |     |  0.019714 |  0.019714 | gvfs-helper  | cache/url:https://wbp-adoprx.microsoft.engineering/ba47400f-eebe-4850-a8bf-ef694ef81414
11:34:38.368935 gvfs-helper-client.c:494     | d1 | main                     | region_enter | r1  |  0.148701 |           | gh-client    | ..label:objects/get
11:34:38.369717 run-command.c:722            | d3 | main                     | child_start  |     |  0.020909 |           |              | [ch0] class:cred argv:['/usr/local/share/gcm-core/git-credential-manager-core get']
11:34:39.588241 run-command.c:979            | d3 | main                     | child_exit   |     |  1.239429 |  1.218520 |              | [ch0] pid:41092 code:0
11:34:39.589029 gvfs-helper.c:1151           | d3 | main                     | region_enter |     |  1.240224 |           | gvfs-helper  | label:GET/objects(cs)
11:34:40.959486 gvfs-helper.c:1177           | d3 | main                     | data         |     |  2.610680 |  1.370456 | gvfs-helper  | ..GET/objects(cs)/nr_bytes:175
11:34:40.961213 gvfs-helper.c:1188           | d3 | main                     | region_leave |     |  2.612408 |  1.372184 | gvfs-helper  | label:GET/objects(cs)
11:34:40.961237 run-command.c:722            | d3 | main                     | child_start  |     |  2.612431 |           |              | [ch1] class:cred argv:['/usr/local/share/gcm-core/git-credential-manager-core store']
11:34:41.358400 run-command.c:979            | d3 | main                     | child_exit   |     |  3.009584 |  0.397153 |              | [ch1] pid:41110 code:0
11:34:41.358473 run-command.c:722            | d3 | main                     | child_start  |     |  3.009666 |           |              | [ch2] class:cred argv:['/usr/local/share/gcm-core/git-credential-manager-core store']
11:34:41.748518 run-command.c:979            | d3 | main                     | child_exit   |     |  3.399704 |  0.390038 |              | [ch2] pid:41126 code:0
11:34:41.760935 gvfs-helper-client.c:513     | d1 | main                     | region_leave | r1  |  3.540700 |  3.391999 | gh-client    | ..label:objects/get
11:34:41.761697 gvfs-helper-client.c:488     | d1 | main                     | printf       |     |  3.541463 |           |              | ..gh_client__get_immediate: add52b27c06d96ff43fcaa05e20f7ca77921fbae
11:34:41.761723 gvfs-helper-client.c:494     | d1 | main                     | region_enter | r1  |  3.541491 |           | gh-client    | ..label:objects/get
11:34:41.761994 gvfs-helper.c:1151           | d3 | main                     | region_enter |     |  3.413188 |           | gvfs-helper  | label:GET/objects(cs)
11:34:42.241108 gvfs-helper.c:1177           | d3 | main                     | data         |     |  3.892303 |  0.479115 | gvfs-helper  | ..GET/objects(cs)/nr_bytes:182
11:34:42.242342 gvfs-helper.c:1188           | d3 | main                     | region_leave |     |  3.893537 |  0.480349 | gvfs-helper  | label:GET/objects(cs)
11:34:42.253276 gvfs-helper-client.c:513     | d1 | main                     | region_leave | r1  |  4.033042 |  0.491551 | gh-client    | ..label:objects/get

**Comment by derrickstolee** [comment]
If you have deleted your shared object cache, then the first thing you should do to repopulate it is run `git fetch`. This will download precomputed packs full of commits and trees to minimize the number of single-object requests that you need for other Git commands.
