### ISSUE TITLE
`git reset --hard` will re-rceiving packfile objects

### ISSUE THREAD

**Issue by miku1958** [microsoft/git#552]
I delete my shared cache and run these to rebuild the cache

```
scalar reconfigure --all
git maintenance run --task=prefetch
git maintenance run --task=incremental-repack
git maintenance run --task=pack-refs
git maintenance run --task=loose-objects
git maintenance run --task=commit-graph
```

And it finish with a new cache of only 4G in size and 127 items, and all git commands completed quickly and properly, which was nice.

Until I ran `git reset --hard`, it started download many pack files again. Is this as expected?

This is the call path
>17:11:50.975285 common-main.c:49             | d0 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
17:11:50.975844 common-main.c:50             | d0 | main                     | start        |     |  0.001298 |           |              | git reset --hard
17:11:50.976446 repository.c:136             | d0 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
17:11:50.977486 git.c:533                    | d0 | main                     | cmd_name     |     |           |           |              | reset (reset)
17:11:50.981984 midx.c:173                   | d0 | main                     | data         | r1  |  0.007440 |  0.007440 | midx         | load/num_packs:27
17:11:50.982004 midx.c:174                   | d0 | main                     | data         | r1  |  0.007462 |  0.007462 | midx         | load/num_objects:6902420
17:11:50.985790 builtin/reset.c:468          | d0 | main                     | cmd_mode     |     |           |           |              | hard
17:11:50.985914 read-cache.c:2490            | d0 | main                     | region_enter | r1  |  0.011372 |           | index        | label:do_read_index .git/index
17:11:50.986423 read-cache.c:2495            | d0 | main                     | region_leave | r1  |  0.011880 |  0.000508 | index        | label:do_read_index .git/index
17:11:50.986481 fsmonitor-ipc.c:80           | d0 | main                     | region_enter |     |  0.011939 |           | fsm_client   | label:query
17:11:50.986493 fsmonitor-ipc.c:81           | d0 | main                     | data         |     |  0.011952 |  0.000013 | fsm_client   | ..query/command:1669885910986479000
17:11:50.986505 ...ipc/ipc-unix-socket.c:162 | d0 | main                     | region_enter |     |  0.011964 |           | ipc-client   | ..label:try-connect
17:11:50.986515 ...ipc/ipc-unix-socket.c:163 | d0 | main                     | data         |     |  0.011973 |  0.000009 | ipc-client   | ....try-connect/path:.git/fsmonitor--daemon.ipc
17:11:50.986588 ...ipc/ipc-unix-socket.c:169 | d0 | main                     | data         |     |  0.012046 |  0.000082 | ipc-client   | ....try-connect/state:0
17:11:50.986600 ...ipc/ipc-unix-socket.c:170 | d0 | main                     | region_leave |     |  0.012058 |  0.000094 | ipc-client   | ..label:try-connect
17:11:50.986608 ...ipc/ipc-unix-socket.c:200 | d0 | main                     | region_enter |     |  0.012066 |           | ipc-client   | ..label:send-command
17:11:50.986744 ...ipc/ipc-unix-socket.c:217 | d0 | main                     | region_leave |     |  0.012200 |  0.000134 | ipc-client   | ..label:send-command
17:11:50.986763 fsmonitor-ipc.c:94           | d0 | main                     | data         |     |  0.012221 |  0.000282 | fsm_client   | ..query/response-length:45
17:11:50.986771 fsmonitor-ipc.c:131          | d0 | main                     | region_leave |     |  0.012230 |  0.000291 | fsm_client   | label:query
17:11:50.986779 fsmonitor.c:338              | d0 | main                     | data         |     |  0.012238 |  0.012238 | fsm_client   | query/trivial-response:1
17:11:50.986791 fsmonitor.c:439              | d0 | main                     | region_enter | r1  |  0.012249 |           | fsmonitor    | label:apply_results
17:11:50.986819 fsmonitor.c:500              | d0 | main                     | region_leave | r1  |  0.012277 |  0.000028 | fsmonitor    | label:apply_results
17:11:50.987344 read-cache.c:2490            | d0 | main                     | region_enter | r1  |  0.012802 |           | index        | label:do_read_index .git/index
17:11:50.987386 read-cache.c:2495            | d0 | main                     | region_leave | r1  |  0.012844 |  0.000042 | index        | label:do_read_index .git/index
17:11:50.989617 unpack-trees.c:1903          | d0 | main                     | region_enter |     |  0.015072 |           | unpack_trees | label:unpack_trees
17:11:50.989635 unpack-trees.c:1907          | d0 | main                     | region_enter | r1  |  0.015093 |           | unpack_trees | ..label:unpack_trees
17:11:50.990354 progress.c:268               | d0 | main                     | region_enter | r1  |  0.015812 |           | progress     | ....label:Updating index flags
17:11:50.990370 unpack-trees.c:1776          | d0 | main                     | region_enter | r1  |  0.015828 |           | unpack_trees | ......label:clear_ce_flags/0x00000000_0x02000000
17:11:50.990378 unpack-trees.c:1790          | d0 | main                     | region_leave | r1  |  0.015837 |  0.000009 | unpack_trees | ......label:clear_ce_flags/0x00000000_0x02000000
17:11:50.990387 progress.c:340               | d0 | main                     | data         | r1  |  0.015845 |  0.000033 | progress     | ......total_objects:0
17:11:50.990395 progress.c:346               | d0 | main                     | region_leave | r1  |  0.015853 |  0.000041 | progress     | ....label:Updating index flags
17:11:50.990408 unpack-trees.c:2010          | d0 | main                     | region_enter | r1  |  0.015866 |           | unpack_trees | ....label:traverse_trees
17:11:58.367682 unpack-trees.c:2012          | d0 | main                     | region_leave | r1  |  7.393138 |  7.377272 | unpack_trees | ....label:traverse_trees
17:11:58.370546 progress.c:268               | d0 | main                     | region_enter | r1  |  7.396003 |           | progress     | ....label:Updating index flags
17:11:58.370566 unpack-trees.c:1776          | d0 | main                     | region_enter | r1  |  7.396024 |           | unpack_trees | ......label:clear_ce_flags/0x00080000_0x42000000
17:11:58.370592 name-hash.c:585              | d0 | main                     | region_enter | r1  |  7.396050 |           | index        | ........label:name-hash-init
17:11:58.390203 name-hash.c:606              | d0 | main                     | region_leave | r1  |  7.415658 |  0.019608 | index        | ........label:name-hash-init
17:11:58.398287 unpack-trees.c:1790          | d0 | main                     | region_leave | r1  |  7.423743 |  0.027719 | unpack_trees | ......label:clear_ce_flags/0x00080000_0x42000000
17:11:58.398308 progress.c:340               | d0 | main                     | data         | r1  |  7.423767 |  0.027764 | progress     | ......total_objects:165258
17:11:58.398315 progress.c:346               | d0 | main                     | region_leave | r1  |  7.423774 |  0.027771 | progress     | ....label:Updating index flags
17:11:58.401898 unpack-trees.c:424           | d0 | main                     | region_enter |     |  7.427355 |           | unpack_trees | ....label:check_updates
17:11:58.405074 progress.c:268               | d0 | main                     | region_enter | r1  |  7.430530 |           | progress     | ......label:Updating files
17:11:59.034529 promisor-remote.c:249        | d0 | main                     | data         | r1  |  8.059986 |  0.629456 | bug          | ........fetch_objects/gvfs-helper:163459

**Comment by derrickstolee** [comment]
Yes, it is expected because the prefetch only downloaded commits and trees and Git is trying to resolve your worktree files against a record of Git blobs, which are no longer on your machine. It needs to download them again.
