### ISSUE TITLE
Debian package download link in readme links to a 404

### ISSUE THREAD

**Issue by abstractionmage** [microsoft/git#554]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

The installation instructions for Ubuntu/Debian based Linux distributions in this repository's README.md feature a wget download from a nonexistant webpage:

```wget -O microsoft-git.deb https://github.com/microsoft/git/releases/download/v2.33.0.vfs.0.0/microsoft-git_2.33.0.vfs.0.0.deb```

Running this command results in an `ERROR 404: Not Found.`, which prevents the installation instructions for Ubuntu/Debian from being successful.

**Comment by derrickstolee** [comment]
Sorry about this. We stopped creating `.deb` packages because of binary compatibility issues across Ubuntu versions. We should update the README, but in the meantime you can use the [install from source instructions](https://github.com/microsoft/git#other-distributions) to install on Linux.

**Comment by ldennington** [comment]
@abstractionmage - can you try this command to get the latest package?

```
wget -O microsoft-git.deb https://github.com/microsoft/git/releases/download/v2.39.1.vfs.0.0/microsoft-git_2.39.1.vfs.0.0.deb
```

Alternatively, if you need `2.33.0.vfs.0.0` specifically, the link in the `README` is missing `amd64` in the asset name. This command should work instead:

```
wget -O microsoft-git.deb https://github.com/microsoft/git/releases/download/v2.33.0.vfs.0.0/microsoft-git_2.33.0.vfs.0.0_amd64.deb
```

I'll update the `README` in the meantime to remove specific versions.

**Comment by abstractionmage** [comment]
Thanks, these commands work.
