### ISSUE TITLE
Git executable for MacOS is not released for ARM (AppleSilicon)

### ISSUE THREAD

**Issue by hi-kumar** [microsoft/git#556]
Git binaries are published for MacOS but are Intel-only (x86_64). ARM (Apple Silicon) executable is not published today. AppleSilicon/ARM is the primary architecture on Apple platforms for new devices. The older Intel machines are being dropped from support by Apple. For example, MacPro (2012/2013) dropped from the current MacOS Ventura (13.1). 

 - [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen) or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.vfs.0.0
cpu: x86_64
built from commit: 0de34d54680002380b4e1adad74db64a34e03053
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of MacOS are you running?

```
MacOS Ventura 13.1 - AppleSilicon M1 Max
```

### Details

 - Which terminal/shell are you running Git from?

** Zsh **

 - What commands did you run to trigger this issue?

```
> file /usr/local/bin/git
```
 - What did you expect to occur after running these commands?

```
 (for architecture arm64):	Mach-O 64-bit executable arm64
```

 - What actually happened instead?

```
/usr/local/bin/git: Mach-O 64-bit executable x86_64
```

**Comment by eschwieb** [comment]
I would expect this to be a hard requirement by this summer or fall 2023.

**Comment by keanenwold** [comment]
Hello @HiKumar-MS , apologies for the delay. 

We believe the existing intel builds should run without issue and that we do not anticipate any performance differences. We rely heavily on GitHub Actions for Release Engineering and there are not currently any M1 runner available to us. Once M1 runners are available, we can revisit this topic. 

Thank you.

**Comment by keanenwold** [comment]
Tracking in a [new issue](https://github.com/microsoft/git/issues/565) for calendar Q4 execution.
