### ISSUE TITLE
Git maintenance scheduling impacting scalability of large repos.

### ISSUE THREAD

**Issue by jambar42** [microsoft/git#592]
https://github.com/microsoft/git/blob/0e35ce97ed2ff103a8416414228992e65dc233e9/builtin/gc.c#L2050

Currently the git maintenance tasks scheduling on Windows machines all have a common start time and repeat scheduling. In large repositories with thousands of downstream clones, this results in every local repo clone running maintenance tasks simultaneously, which is negatively impacting the backend infrastructure.

Suggestion: Change these scheduling triggers to be at startup or at logon and then repeat at the normal cadence (hourly, daily, weekly) indefinitely, in order to stagger the maintenance tasks triggering.

**Comment by dscho** [comment]
See https://github.com/gitgitgadget/git/pull/1567 and https://github.com/microsoft/git/pull/597
