### ISSUE TITLE
git fetch --depth 1 is not working

### ISSUE THREAD

**Issue by miku1958** [microsoft/git#619]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.43.0.vfs.0.0.rc0
cpu: arm64
built from commit: 3f0dcb0df0f55e5943c51c6fde26897e9b4a7d2e
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

macOS 14.1.1
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

zsh

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch --depth 1 
```
 - What did you expect to occur after running these commands?

only fetch the last commit for me, like:
<img width="162" alt="image" src="https://github.com/microsoft/git/assets/24806909/74e5175a-c4b3-426e-b258-e3419b864a3a">

 - What actually happened instead?

Starting from the current commit to the latest commit are fetched down
<img width="200" alt="image" src="https://github.com/microsoft/git/assets/24806909/7a006b73-25fa-4394-878f-fc866d64a252">

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [ ] Public repo: **insert URL here**
   * [ ] Windows monorepo
   * [x] Office monorepo
   * [ ] Other Microsoft-internal repo: **insert name here**
   * [ ] Other internal repo.

**Comment by derrickstolee** [comment]
You shouldn't be using `git fetch --depth` in this scenario. It is disabled for repositories using the GVFS protocol, by design, since the client is not receiving objects from the origin server via the Git protocol.

**Comment by miku1958** [comment]
Hi @derrickstolee , I know GVFS protocol will delay download objects until I checkout the commit.

The reason I do this is to minimize the number of local commits that I don't need.

**Comment by dscho** [comment]
> The reason I do this is to minimize the number of local commits that I don't need.

Unfortunately, there is no option in Git yet to do maintenance in partial clones where the goal is size-on-disk reduction. @miku1958 how about sending this feature request to the Git mailing list? See https://git-scm.com/community for more details.

**Comment by miku1958** [comment]
Ok I'll do that, thanks!
