### ISSUE TITLE
`git for-each-repo` stops on non-existent repo (Windows?)

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#623]
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.43.0.vfs.0.0
cpu: x86_64
built from commit: b7a6ed788a205fb2c0013111d277b4c9d6ab35bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.23612.1000]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I removed a repository that was previously registered with background maintenance.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash or CMD.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global --add my.config BOGUS-PATH
git config --global --add my.config C:/Real/Path
$ git for-each-repo --config=my.config status
fatal: cannot change to 'BOGUS-PATH': No such file or directory
```

 - What did you expect to occur after running these commands?

The iteration of `git for-each-repo` to continue on all repos, ignoring the non-existent repo.

 - What actually happened instead?

The first non-existent repo stopped the loop.

### Additional Context / Impact

This affects background maintenance for users who have deleted a repo. It shuts down all background maintenance for repos later in the `maintenance.repo` multi-config.

**Comment by dscho** [comment]
> The first non-existent repo stopped the loop.

This is indeed the case 😞:

https://github.com/git/git/blob/v2.43.0/builtin/for-each-repo.c#L58-L59

It would probably make sense to retain the ability to stop on the first failure, but make that an option, by default continuing (but of course still exiting with an error if the operation failed in at least one repository).

**Comment by dscho** [comment]
Sketch of the functional change I am proposing:

```diff
diff --git a/builtin/for-each-repo.c b/builtin/for-each-repo.c
index 28186b30f548..35ab7f34ca15 100644
--- a/builtin/for-each-repo.c
+++ b/builtin/for-each-repo.c
@@ -32,6 +32,7 @@ static int run_command_on_repo(const char *path, int argc, const char ** argv)
 int cmd_for_each_repo(int argc, const char **argv, const char *prefix)
 {
 	static const char *config_key = NULL;
+	int stop_on_error = 0;
 	int i, result = 0;
 	const struct string_list *values;
 	int err;
@@ -39,6 +40,8 @@ int cmd_for_each_repo(int argc, const char **argv, const char *prefix)
 	const struct option options[] = {
 		OPT_STRING(0, "config", &config_key, N_("config"),
 			   N_("config key storing a list of repository paths")),
+		OPT_BOOL(0, "stop-on-error", &stop_on_error,
+			 N_("stop at the first repository where the operation failed")),
 		OPT_END()
 	};
 
@@ -55,8 +58,9 @@ int cmd_for_each_repo(int argc, const char **argv, const char *prefix)
 	else if (err)
 		return 0;
 
-	for (i = 0; !result && i < values->nr; i++)
-		result = run_command_on_repo(values->items[i].string, argc, argv);
+	for (i = 0; (!stop_on_error || !result) && i < values->nr; i++)
+		if (run_command_on_repo(values->items[i].string, argc, argv))
+			result = 1;
 
 	return result;
 }
```

**Comment by derrickstolee** [comment]
> Sketch of the functional change I am proposing:

That would be the backwards-compatible fix. The other approach would be to change behavior by attempting all repos and returning success only if every repo succeeded. But Git doesn't typically do backwards-incompatible things. Who knows who depends on this early termination behavior?

Please also update the background maintenance schedule to include `--stop-on-error` on its use of `for-each-repo` to auto-heal users when they reconfigure background maintenance.
