### ISSUE TITLE
Release for v2.44.0.vfs.0.3 ? Patch for sparse-checkout crashes

### ISSUE THREAD

**Issue by kyle-rader-msft** [microsoft/git#643]
Hello friends!

I'm hoping to use this issue to track getting a release made containing #639. This crash is impacting close to 400 developers now + automated scenarios within the OPG group.

We'd love to get this fix rollout out through Winget as soon as we can :). If there's anything we can do to help dogfood or test such a release please let us know!

**Comment by kyle-rader-msft** [comment]
@dscho , @jeffhostetler any eta on releasing the sparse-checkout crash fix?

**Comment by dscho** [comment]
The synchronization with Git v2.45.0 [scheduled for April 29th](https://gh.io/gitCal) presents us with an opportunity to work around limited funding and nevertheless provide you with the latest updates, including the fixes you need so dearly. We intend to fast-track v2.45.0.vfs.0.0.

**Comment by dscho** [comment]
See https://github.com/microsoft/git/releases/tag/v2.45.0.vfs.0.0
