### ISSUE TITLE
git difftool with visual editor takes 4.5 seconds to open next file

### ISSUE THREAD

**Issue by HassanAhmadAli** [microsoft/git#657]
i configured a gui application to be used with git core.editor "vscode" , the application work perfectly as a git mergetool but it takes 4.5 second or more to switch to the next file when running 'git difftool', the issue is not only with vscode as i tried other visual code editors and all of them take long time, but the command runs extremely fast with cli based applications.

then...

i tried using git with wsl in windows and set vscode as the default code editor for git and it takes fraction of a second to switch files `git difftool`.
both on the same machine *git with wsl* is very much faster with GUI than git for windows 

 - [ ] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?
 - 64 bit

```
$ git --version --build-options

**
cpu: x86_64
built from commit: b68812e6facef46153bdeb3d79c1b8f353b8e94d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
**
```

Are you using Scalar or VFS for Git?

** no **

If VFS for Git, then what version?

```
$ gvfs version

** gvfs: The term 'gvfs' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
64 bit windows 10
```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

**Comment by dscho** [comment]
Closing in favor of https://github.com/git-for-windows/git/issues/4998
