### ISSUE TITLE
v2.45.2.vfs.0.2: performance regression in pathspec checkouts

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#673]
### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

v2.45.2.vfs.0.2
```

Are you using Scalar or VFS for Git?

VFS for Git

If VFS for Git, then what version? (latest)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git restore .
```

This used to be fast, but now is slow.

> Note: I'm passing this report from an internal user. I've recommended that they use `git reset --hard` as a way that should avoid the current regression as well as communicating to Git the full expectation of what is going on, but this performance regression should be avoided. Unfortunately, this also means the issue fixed by #658 is not fully fixed.

**Comment by dscho** [comment]
Please test [v2.45.2.vfs.0.3](https://github.com/microsoft/git/releases/tag/v2.45.2.vfs.0.3).
